### ISSUE TITLE
Update Method names

### ISSUE THREAD

**Issue by ryzhman** [OlgaDiakonova/JDBC#1]
https://github.com/OlgaDiakonova/JDBC/blob/7298ca51c1a9e01ec06d6cc8dbde3cc67b404409/src/DataLoad.java#L8
This method accepts Merchant, but is supposed to add payments. I would pass Payments as a separate object or rename the method

The class itself has an incorrect naming. Follow the Repository - Service - Entity pattern. Place corresponding classes in a separate packages. 

`Service.getConnection` is not a proper naming of a class with utils. Better off to name it DBUtils

**Comment by OlgaDiakonova** [comment]
done by code refactoring
