### ISSUE TITLE
Extract to a separate method

### ISSUE THREAD

**Issue by ryzhman** [OlgaDiakonova/JDBC#2]
https://github.com/OlgaDiakonova/JDBC/blob/7298ca51c1a9e01ec06d6cc8dbde3cc67b404409/src/DataLoad.java#L8

Code responsible for adding a payment should be extracted into a separate Repository and should be reused in your service class.
It is service class that should coordinate work of all the repositories. Ie, `MerchantService.addPayment` uses MerchantRepository to get a Merchant Id, and then calls PaymentRepository to add one payment at a time. 

It doesn't make sense to have a method that will add all payments at a time, since it is just a duplication of a single addPayment() method

**Comment by OlgaDiakonova** [comment]
done by code refactoring
